### ISSUE TITLE
Gráfico não fica completamente visível em tela cheia do navegador.

### ISSUE THREAD

**Issue by Maracujacake** [danieldribeiro/weather-webapp#1]
Em vista de contribuir para este belo projeto, venho por meio deste issue reportar um comportamento que creio ser inesperado:

![image](https://github.com/danieldribeiro/weather-webapp/assets/74564883/335a5918-3614-4f91-9332-d37b77eb8723)

Como é possível observar, ao abrir a página em tela cheia no navegador Microsoft Edge, o gráfico de observação da temperatura fica só parcialmente visível, enquanto ao diminuir a tela, pode-se observá-lo normalmente:

![image](https://github.com/danieldribeiro/weather-webapp/assets/74564883/a5e4fb03-285a-411c-ab88-e53987a56da2)

Ficou muito fera o trabalho! :)

**Comment by danieldribeiro** [comment]
Muito obrigado pelo feedback, irmão! Fiz os ajustes e agora deve estar tudo correto
